var Turn=0,sbl=["O","X"],Brd=[],RB=0,cnt="F;B;R;L;FR;BR;FL;BL",RBs=18,cr=["lightgray","white"],bc=["palevioletred","lightsteelblue"]
function Set(crd){if(Turn==0)Wtr();if(Controls(crd).innerHTML==""&&Controls(crd).style.backgroundColor!=bc[(Turn+1)%2]){Controls(crd).innerHTML=sbl[Turn%2];Controls(crd).style.backgroundColor=cr[(Asc(Mid(crd,0,1))+Val(Mid(crd,1,1)))%2];Rng(crd);Turn++;Wtr()}}
function Rng(crd){var c1=Asc(Mid(crd,0,1)),c2=Val(Mid(crd,1,1));for(cd1=65;cd1<74;cd1++){var d1c2=Chr(cd1)+c2;if(Controls(d1c2).innerHTML==sbl[Turn%2]&&d1c2!=crd){for(cd2=1;cd2<10;cd2++){var c1d2=Chr(c1)+cd2;if(Controls(c1d2).innerHTML==sbl[Turn%2]&&Controls(Chr(cd1)+cd2).innerHTML==sbl[Turn%2]&&c1d2!=crd){Blk(Chr(cd1)+cd2,crd)}}}}}
function Blk(tg1,tg2){var t11=Asc(Mid(tg1,0,1)),t21=Asc(Mid(tg2,0,1)),t12=Val(Mid(tg1,1,1)),t22=Val(Mid(tg2,1,1));for(var cd1=65;cd1<74;cd1++){for(var cd2=1;cd2<10;cd2++){if(cd1>=t11&&cd2>=t12&&cd1<=t21&&cd2<=t22||cd1<=t11&&cd2<=t12&&cd1>=t21&&cd2>=t22||cd1>=t11&&cd2<=t12&&cd1<=t21&&cd2>=t22||cd1<=t11&&cd2>=t12&&cd1>=t21&&cd2<=t22)Clr(Chr(cd1)+cd2,sbl[Turn%2])}}}
function Cln(msg,tgt){var ck;if(msg!=""){ck=confirm(msg)}else{ck=true}if(ck==true){for(cd1=65;cd1<74;cd1++){for(cd2=1;cd2<10;cd2++){if(Instr(Controls(Chr(cd1)+cd2).innerHTML,tgt)>-1){Controls(Chr(cd1)+cd2).innerHTML="";Controls(Chr(cd1)+cd2).title=""}if(Controls(Chr(cd1)+cd2).style.backgroundColor!="dimgray"||tgt==" "||tgt=="")Controls(Chr(cd1)+cd2).style.backgroundColor=cr[(cd1+cd2)%2]}}if(tgt==""){Turn=0;Brd=[];if(RB==1)RdB()}}}
function Rul(){var OA=0,XA=0,PA=0;for(cd1=65;cd1<74;cd1++){for(cd2=1;cd2<10;cd2++){if(Controls(Chr(cd1)+cd2).innerHTML==""&&Controls(Chr(cd1)+cd2).style.backgroundColor!="dimgray"){PA++;switch(Controls(Chr(cd1)+cd2).style.backgroundColor){case bc[0]:OA++;break;case bc[1]:XA++}}}}if(OA>=PA/2)Cln("O Win.","");if(XA>=PA/2)Cln("X Win.","");if(PA==0)Cln("Draw","")}
function Wtr(){var s="";for(cd1=65;cd1<74;cd1++){for(cd2=1;cd2<10;cd2++){switch(Controls(Chr(cd1)+cd2).innerHTML){case"O":s+="0";break;case"X":s+="1";break;case" ":s+="3";break;default:var clr=Controls(Chr(cd1)+cd2).style.backgroundColor;if(clr==bc[1]){s+="5"}else if(clr==bc[0]){s+="4"}else{s+="2"}}}}Brd[Turn]=s;Rul()}
function Rdr(turn){if(turn>=0&&Brd[turn]!=""){var s=0;for(cd1=65;cd1<74;cd1++){for(cd2=1;cd2<10;cd2++){var sym="",bgc=cr[(cd1+cd2)%2];switch(Mid(Brd[turn],s,1)){case"0":sym="O";break;case"1":sym="X";break;case"3":sym=" ";bgc="dimgray";break;case"4":bgc=bc[0];break;case"5":bgc=bc[1]}Controls(Chr(cd1)+cd2).innerHTML=sym;Controls(Chr(cd1)+cd2).style.backgroundColor=bgc;s++;Turn=turn}}}Rul()}
function RdB(){var n=0,ck=0;if(RBs>27)RBs=27;while(n<RBs){var cd1=Val(Rnd()*9+65),cd2=Val(Rnd()*9+1),crd=Chr(cd1)+cd2;if(Controls(crd).innerHTML==""&&Val(cd1+cd2)%2==0){Controls(crd).style.backgroundColor="dimgray";Controls(crd).innerHTML=" ";n++}ck++;if(ck>81)break}}
function Clr(crd,sym){var clr={"O":bc[0],"X":bc[1]};if(Controls(crd).innerHTML==""&&Controls(crd).style.backgroundColor!=bc[0]&&Controls(crd).style.backgroundColor!=bc[1]){Controls(crd).style.backgroundColor=clr[sym]}}