var Turn=0,sbl=["O","X"],Brd=[],RS=0,RB=0,cnt="F;B;R;L;FR;BR;FL;BL",RBs=18,RL=0
function Set(crd){if(Turn==0)Wtr();if(Cnt(sbl[Turn%2],crd)==1&&Controls(crd).innerHTML==""){Controls(crd).innerHTML=sbl[Turn%2];Turn++;Wtr()}}
function Cnt(sym,crd){var ord=Split(cnt,";");if(Turn<2)return 1;for(i in ord){if(Controls(Crd(ord[i],crd))&&Controls(Crd(ord[i],crd)).innerHTML==sym){return 1}}return 0}
function Crd(arw,crd){var arw=Split(arw,""),x=0,y=0;for(var i in arw){switch(arw[i]){case"F":y--;break;case"B":y++;break;case"R":x++;break;case"L":x--;break}}return Chr(Asc(Mid(crd,0,1))+x)+Val(Val(Mid(crd,1,1))+y)}
function Rul(){var OA=0,XA=0,PA=0;for(cd1=65;cd1<74;cd1++){for(cd2=1;cd2<10;cd2++){var Os=Cnt("O",Chr(cd1)+cd2),Xs=Cnt("X",Chr(cd1)+cd2),rs="";if(Os==1)rs="O0";if(Xs==1)rs="X0";if(Os==1&&Xs==1)rs="P0";Controls(Chr(cd1)+cd2).title=rs}}for(n=0;n<9;n++){for(cd1=65;cd1<74;cd1++){for(cd2=1;cd2<10;cd2++){if(Controls(Chr(cd1)+cd2).title==""&&Controls(Chr(cd1)+cd2).innerHTML==""){var ord=Split(cnt,";"),ot=0,xt=0,rs="";for(i in ord){if(Controls(Crd(ord[i],Chr(cd1)+cd2))){if(Controls(Crd(ord[i],Chr(cd1)+cd2)).title=="O"+n)ot=1;if(Controls(Crd(ord[i],Chr(cd1)+cd2)).title=="X"+n)xt=1}}if(ot==1)rs="O";if(xt==1)rs="X";if(ot==1&&xt==1)rs="P";if(rs!="")Controls(Chr(cd1)+cd2).title=rs+Val(n+1)}}}}Cln('','N');for(cd1=65;cd1<74;cd1++){for(cd2=1;cd2<10;cd2++){if(Controls(Chr(cd1)+cd2).innerHTML==""){switch(Mid(Controls(Chr(cd1)+cd2).title,0,1)){case"O":OA++;Clr(Chr(cd1)+cd2,"O");break;case"X":XA++;Clr(Chr(cd1)+cd2,"X");break;case"P":PA++;break}}}}if(PA==0&&Turn>2){if(OA>XA&&Turn%2==1){Cln("O Win.","")}else if(XA>OA){Cln("X Win.","")}else if(OA==XA){Cln("Draw","")}}}
function Cln(msg,tgt){var ck;if(msg!=""){ck=confirm(msg)}else{ck=true}if(ck==true){var cr=["lightgray","white"];for(cd1=65;cd1<74;cd1++){for(cd2=1;cd2<10;cd2++){if(Instr(Controls(Chr(cd1)+cd2).innerHTML,tgt)>=0){Controls(Chr(cd1)+cd2).innerHTML="";Controls(Chr(cd1)+cd2).title=""}if(Controls(Chr(cd1)+cd2).style.backgroundColor!="dimgray"||tgt==" "||tgt=="")Controls(Chr(cd1)+cd2).style.backgroundColor=cr[(cd1+cd2)%2]}}if(tgt==""){Turn=0;Brd=[];if(RS==1)RdS();if(RB==1)RdB()}}}
function Wtr(){var s="";for(cd1=65;cd1<74;cd1++){for(cd2=1;cd2<10;cd2++){switch(Controls(Chr(cd1)+cd2).innerHTML){case"O":s+="0";break;case"X":s+="1";break;case" ":s+="3";break;default:s+="2"}}}Brd[Turn]=s;Rul()}
function Rdr(turn){if(turn>=0&&Brd[turn]!=""){var s=0;for(cd1=65;cd1<74;cd1++){for(cd2=1;cd2<10;cd2++){var sym="";switch(Mid(Brd[turn],s,1)){case"0":sym="O";break;case"1":sym="X";break;case"3":sym=" ";break;default:sym=""}Controls(Chr(cd1)+cd2).innerHTML=sym;s++;Turn=turn}}Rul()}}
function RdS(){var Os=["E4","E6","D5","F5"],Xs=["D4","D6","F4","F6"];Set(Os[Val(Rnd()*4)]);Set(Xs[Val(Rnd()*4)])}
function RdB(){var n=0,ck=0;if(RBs>27)RBs=27;while(n<RBs){var cd1=Val(Rnd()*9+65),cd2=Val(Rnd()*9+1),crd=Chr(cd1)+cd2;if(Controls(crd).innerHTML==""&&Val(cd1+cd2)%2==0){Controls(crd).style.backgroundColor="dimgray";Controls(crd).innerHTML=" ";n++}ck++;if(ck>81)break}}
function Clr(crd,sym){var clr={"O":["maroon","crimson"],"X":["navy","royalblue"]},c=Asc(Mid(crd,0,1))+Val(Mid(crd,1,1));if(RL==1){Controls(crd).style.backgroundColor=clr[sym][c%2]}}